@startuml
participant index.ts
participant JoyJs
participant ComponentFn
participant componentInstance
participant renderJoy

note over renderJoy: used inside ComponentFn
index.ts -> JoyJs: create(ComponentFn)
JoyJs -> ComponentFn: run ComponentFn(props, {renderJoy})
note over ComponentFn: provides renderJoy to ComponentFn.
JoyJs --> renderJoy
JoyJs -> componentInstance: initiate componentInstance
componentInstance <-- renderJoy: useState()
componentInstance <-- renderJoy: useEffect()
componentInstance <-- renderJoy: createRoot(tag)
componentInstance <-- renderJoy: create(tagOrComponentFn)
componentInstance --> index.ts: append children to root element

@enduml
