@startuml
participant index.ts
participant JoyJs
participant ComponentFn
participant componentInstance
participant renderJoy


index.ts -> JoyJs: create(ComponentFn)
note over ComponentFn: provides renderJoy to ComponentFn.
JoyJs -> ComponentFn: run ComponentFn(props, {renderJoy})
ComponentFn -> componentInstance: initiate componentInstance
componentInstance <-- renderJoy: useState()
componentInstance <-- renderJoy: createRoot(tag)
componentInstance <-- renderJoy: create(tagOrComponentFn)
componentInstance --> index.ts: append children to root element

@enduml
